# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
