# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-14 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0005_auto_20170614_1908'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmenthistorymodel',
            unique_together=set([('appointment_id', 'appointment_start_time')]),
        ),
    ]
