# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0006_auto_20170614_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistorymodel',
            name='statusTime',
            field=models.DateTimeField(null=True),
        ),
    ]
