# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0007_auto_20170614_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistorymodel',
            name='statusTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
