# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-14 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0009_appointmenthistorymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistorymodel',
            name='check',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
