# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0010_appointmenthistorymodel_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistorymodel',
            name='check',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
